#!/usr/bin/env python3
"""
Generate C header with bitmap glyphs for ESP32.
Renders 0-9, space, 'x' from Kario font (matches POC look).
Run from project root: python esp32/tools/generate_font.py
Output: esp32/include/font_glyphs.h
"""

import os
import sys

# Add testing for font path
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
TESTING_DIR = os.path.join(PROJECT_ROOT, "testing")
FONT_PATH = os.path.join(TESTING_DIR, "Kario39C3Var-Roman.ttf")
OUTPUT_HEADER = os.path.join(PROJECT_ROOT, "esp32", "include", "font_glyphs.h")

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("Install Pillow: pip install Pillow")
    sys.exit(1)


def main():
    if not os.path.isfile(FONT_PATH):
        print(f"Font not found: {FONT_PATH}")
        sys.exit(1)

    # Chars we need: 0-9, space, 'x'
    chars = "0123456789 x"
    font_size = 22
    font_width_axis = 50  # Condensed for narrow display

    font = ImageFont.truetype(FONT_PATH, font_size)
    try:
        axes = font.get_variation_axes()
        values = []
        for ax in axes:
            tag = (ax.get("tag") or b"").decode("utf-8", errors="ignore").lower()
            values.append(font_width_axis if tag == "wdth" else ax["default"])
        font.set_variation_by_axes(values)
    except (OSError, AttributeError):
        pass

    glyphs = {}
    for c in chars:
        bbox = font.getbbox(c) if hasattr(font, "getbbox") else font.getmask(c).getbbox()
        if not bbox:
            glyphs[c] = (0, 0, [])
            continue
        w = bbox[2] - bbox[0]
        h = bbox[3] - bbox[1]
        img = Image.new("1", (w, h), 0)
        draw = ImageDraw.Draw(img)
        draw.text((-bbox[0], -bbox[1]), c, fill=1, font=font)
        # Pack 1bpp: each row -> (w+7)//8 bytes, MSB first (pixel 0 in bit 7)
        data = []
        bytes_per_row = (w + 7) // 8
        for y in range(h):
            for byte_idx in range(bytes_per_row):
                b = 0
                for bit in range(8):
                    x = byte_idx * 8 + (7 - bit)
                    if x < w and img.getpixel((x, y)):
                        b |= 1 << bit
                data.append(b)
        glyphs[c] = (w, h, data)

    # Write C header
    os.makedirs(os.path.dirname(OUTPUT_HEADER), exist_ok=True)
    with open(OUTPUT_HEADER, "w") as f:
        f.write("// Auto-generated by tools/generate_font.py - do not edit\n")
        f.write("#ifndef FONT_GLYPHS_H\n#define FONT_GLYPHS_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("// Glyph: width, height, bitmap (1bpp, row-major)\n")
        f.write("typedef struct { uint8_t w; uint8_t h; const uint8_t *bits; } glyph_t;\n\n")

        for c in chars:
            name = f"digit_{c}" if c.isdigit() else ("space" if c == " " else "chr_x")
            w, h, data = glyphs[c]
            f.write(f"static const uint8_t glyph_{name}_bits[] = {{\n  ")
            for i, b in enumerate(data):
                f.write(f"0x{b:02x},")
                if (i + 1) % 12 == 0:
                    f.write("\n  ")
            f.write("\n};\n\n")

        f.write("static const glyph_t GLYPHS[] = {\n")
        for c in chars:
            name = f"digit_{c}" if c.isdigit() else ("space" if c == " " else "chr_x")
            w, h, _ = glyphs[c]
            f.write(f"  {{ .w = {w}, .h = {h}, .bits = glyph_{name}_bits }},  /* '{c}' */\n")
        f.write("};\n\n")
        f.write("#define GLYPH_INDEX_0 0\n")
        f.write("#define GLYPH_INDEX_9 9\n")
        f.write("#define GLYPH_INDEX_SPACE 10\n")
        f.write("#define GLYPH_INDEX_X 11\n\n")
        f.write("#endif\n")

    print(f"Generated {OUTPUT_HEADER} with {len(chars)} glyphs")


if __name__ == "__main__":
    main()
